version: '3'

services:
  database:
    image: mongo:latest
    container_name: mongodb-1
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
    driver: local